//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralRepository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CentralDigitalCondoEntities : DbContext
    {
        public CentralDigitalCondoEntities()
            : base("name=CentralDigitalCondoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<SP_DGC_GetAllActiveSubscriptions_Result> SP_DGC_GetAllActiveSubscriptions()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DGC_GetAllActiveSubscriptions_Result>("SP_DGC_GetAllActiveSubscriptions");
        }
    
        public virtual int SP_DGC_SavePasswordDetails(Nullable<long> centralUserId, string newPassword, string newMobileIMEA, string updatedBy, ObjectParameter errorcode)
        {
            var centralUserIdParameter = centralUserId.HasValue ?
                new ObjectParameter("CentralUserId", centralUserId) :
                new ObjectParameter("CentralUserId", typeof(long));
    
            var newPasswordParameter = newPassword != null ?
                new ObjectParameter("NewPassword", newPassword) :
                new ObjectParameter("NewPassword", typeof(string));
    
            var newMobileIMEAParameter = newMobileIMEA != null ?
                new ObjectParameter("NewMobileIMEA", newMobileIMEA) :
                new ObjectParameter("NewMobileIMEA", typeof(string));
    
            var updatedByParameter = updatedBy != null ?
                new ObjectParameter("UpdatedBy", updatedBy) :
                new ObjectParameter("UpdatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DGC_SavePasswordDetails", centralUserIdParameter, newPasswordParameter, newMobileIMEAParameter, updatedByParameter, errorcode);
        }
    }
}
